apiVersion: v1
kind: Service
metadata:
  name: apa000ser
spec:
  selector:
    app: apa000kube
  type: NodePort
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 80
      nodePort: 30080
