apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-custom-liveness
spec:
  containers:
    - name: nginx-container
      image: nginx:1.14
      ports:
        - containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 80
        successThreshold: 1
        failureThreshold: 5
        initialDelaySeconds: 10
        timeoutSeconds: 3
        periodSeconds: 30