
apiVersion: v1
kind: Namespace
metadata:
  name: product

---

apiVersion: v1
kind: Pod
metadata:
  name: myweb
  namespace: product
spec:
  containers:
    - name: nginx-container
      image: nginx:1.14
      ports:
        - containerPort: 80
        - containerPort: 443
      env:
        - name: DB
          value: mydb
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: "1"
          memory: 1Gi