apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: developer
rules:
  - apiGroups: [ "" ]
    verbs: [ "create", "get", "list", "update", "delete" ]
    resources: [ "pods" ]
