apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-resources
spec:
  containers:
    - name: nginx-container
      image: nginx:1.14
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: "1"
          memory: 1Gi
