apiVersion: v1
kind: Pod
metadata:
  name: pod-ml
spec:
  containers:
    - name: tensorflow-container
      image: tensorflow/tensorflow:nightly-jupyter
      ports:
        - containerPort: 80
          protocol: TCP
  nodeSelector:
    disktype: ssd
    gpu: "true"
