apiVersion: v1
kind: Pod
metadata:
  name: web-server-pod
  labels:
    role: web-server-pod
spec:
  containers:
    - name: web-server-container
      image: my-web-server
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80