spring:
  datasource:
    url: jdbc:h2:mem:kub-practice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        use_sql_comments: true
        format_sql: true
        highlight_sql: true

logging:
  level:
#    org.hibernate.type.descriptor.sql: trace
    org.hibernate.orm.jdbc.bind: trace
