apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-mainui
spec:
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      name: apache-pod
      labels:
        app: webui
    spec:
      containers:
        - name: apache-container
          image: httpd:2.2