apiVersion: v1
kind: Pod
metadata:
  name: liveness-exam
spec:
  containers:
    - name: busybox-container
      image: busybox
      imagePullPolicy: IfNotPresent
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
      livenessProbe:
        successThreshold: 1
        failureThreshold: 2
        initialDelaySeconds: 10
        periodSeconds: 5
        exec:
          command:
            - ls
            - /tmp/healthy