apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    builder: "seungbok Lee (lsb530@naver.com)"
    buildDate: "20240706"
    image-registry: "https://hub.docker.com/"
spec:
  containers:
    - name: nginx-container
      image: nginx:1.14
      ports:
        - containerPort: 80
          protocol: TCP
